---
services:
  goxlr-utility-api-py:
    build: .
    restart: unless-stopped
    ports:
      - target: 9170
        published: 9170
        protocol: tcp
    volumes:
      - type: volume
        source: goxlr-utility-api-py-data
        target: /data/goxlr-utility-api-py

volumes:
  goxlr-utility-api-py-data: {}
