---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  # schedule:
  #   - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-module:
    uses: timmo001/workflows/.github/workflows/deploy-python-linux.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    with:
      code-path: module
      module-name: goxlrutilityapi
      use-incremental: true
